Todolist
wolox-training/aos-react-native pull request #1
Opened 2019-01-17 21:20 UTC by Anisospina

## Summary

Todo List:

- Add new Item
- Checked Item
- Removed Item

## Screenshots

![todo](https://user-images.githubusercontent.com/13072856/51349589-d0505e80-1a73-11e9-97de-65b549bc8ad6.gif)

## Trello Card

https://trello.com/c/RAJYbkLM/1-componentes-i-yet-another-todo-list

2019-01-18 13:48 UTC, guidoprinc requested changes

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/App.js
> + */
delete this

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/App.js
> +          <ListView
check `FlatList` component and try using it here for better render management

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/App.js
> +          }}
extract this into an arrow function above like:
```js
renderSeparator = (sectionId, rowId) => <View key={rowId} style={styles.separator} />;
```
and then calliing it in here as ```renderSeparator={this.renderSeparator}```

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/App.js
> +          }}
check `renderSeparator` comment and apply it i here too

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/App.js
> +    borderColor: '#F5F5F5',
extract all colors in a constant file in `src/constants`

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/src/components/Footer/index.js
> +export default class Footer extends Component {
since this is only a render you can change this into:
```js
const Footer = () => (
  <View>
   ...
  </View>
);
```
or
```js
function Footer() {
return (<View>
   ...
  </View>
);
}
```

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/src/components/Footer/index.js
> + })
extract styles into a `styles.js` file

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/App.js
> +    borderColor: '#F5F5F5',
also extract this styles into a `styles.js` file

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/src/components/Header/index.js
> +export default class Header extends Component {
check `Footer`'s comments and apply them here too

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/src/components/Row/index.js
> +class Row extends Component {
check `Footer`'s comments and apply them here too.
also since you use a prop here you can do it like this:
```js
const Footer = ({ complete }) => (
  <View>
   ...
  </View>
);
```
or
```js
function Footer({ complete }) {
return (<View>
   ...
  </View>
);
}
```

2019-01-18 13:48 UTC, guidoprinc commented on toDoList/src/components/ToDo/index.js
> +export default class ToDo extends Component {
apply `Footer`'s comments in here too

2019-01-21 13:17 UTC, guidoprinc reviewed
Finish this pr before sending the review of the other one

2019-01-21 14:18 UTC, guidoprinc approved these changes

2019-01-21 14:18 UTC, guidoprinc commented on toDoList/src/components/Footer/styles.js
> +    zIndex: 1
remember that `zIndex` only works in ios and you have to use `elevation` for android

2019-01-21 14:31 UTC, Anisospina commented on toDoList/src/components/Footer/styles.js
> +    zIndex: 1
thanks, I had no idea

2019-01-21 15:45 UTC, merged