Book details
wolox-training/aos-react-native pull request #4
Opened 2019-01-23 03:11 UTC by Anisospina

## Summary

- Show detail of book

## Screenshots

![detail](https://user-images.githubusercontent.com/13072856/51580417-67f9e680-1e92-11e9-813e-edf5acf77031.gif)

## Trello Card

https://trello.com/c/IbiSso55/6-componentes-iii-detalle-de-libros

2019-01-23 13:16 UTC, guidoprinc requested changes

2019-01-23 13:16 UTC, guidoprinc commented on toDoList/src/components/Navigation/stackNavigation/index.js
> +    // }
delete comments

2019-01-23 13:16 UTC, guidoprinc commented on toDoList/src/components/Navigation/stackNavigation/index.js
> +};
if you are not using the interpolator then delete it

2019-01-23 13:16 UTC, guidoprinc commented on toDoList/src/screens/BookDetail/index.js
> +        {image_url !== null ? (
`image_url ? ( ... ) : (...)`

2019-01-23 13:16 UTC, guidoprinc commented on toDoList/src/screens/BookDetail/index.js
> +          <Text style={styles.text}>{year}</Text>
you can make an array of elements in the render to map them and not to repeat code, or you can create a component with a pair of strings to reduce half of this

2019-01-23 13:16 UTC, guidoprinc commented on toDoList/src/screens/BookDetail/style.js
> +    backgroundColor: gray_five
from now on, try to be more descriptive with color names, just because in the future there are not a lot of colors in an app and it's easy to reference them with a proper name

2019-01-23 13:16 UTC, guidoprinc commented on toDoList/src/screens/Books/components/row/index.js
> +      <TouchableHighlight underlayColor="#eee" onPress={this.onPress}>
into colors file

2019-01-23 15:18 UTC, Anisospina commented on toDoList/src/screens/Books/components/row/index.js
> +      <TouchableHighlight underlayColor="#eee" onPress={this.onPress}>
What are the chances we could something like an :active pseudo-class?

In fact, how do you do pseudo-classes when you do CSS in JS anyway?


change to TouchableOpacity ....

2019-01-23 18:50 UTC, guidoprinc approved these changes

2019-01-23 18:50 UTC, guidoprinc commented on toDoList/src/screens/BookDetail/index.js
> +      <View style={styles.content}>
extract this into a render function

2019-01-24 15:46 UTC, pabloferro approved these changes

2019-01-24 17:42 UTC, pabloferro requested changes

2019-01-24 17:42 UTC, pabloferro commented on toDoList/src/screens/BookDetail/index.js
> +        {this.detail()}
After testing the app I'd put the details in ScrollView

2019-01-25 14:34 UTC, pabloferro approved these changes

2019-01-25 14:40 UTC, merged